#cloud-config
package_update: true
package_upgrade: false

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

write_files:
  - path: /opt/postgres/docker-compose.yml
    permissions: '0644'
    content: |
      version: "3.9"
      services:
        postgres:
          image: postgres:16
          restart: unless-stopped
          environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
          volumes:
            - /opt/postgres/data:/var/lib/postgresql/data
          ports:
            - "5432:5432"
          healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
      volumes: {}

runcmd:
  # Install Docker CE from official repo
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  # Enable docker & permissions
  - systemctl enable --now docker
  - usermod -aG docker ${ADMIN_USERNAME}

  # Prepare data dir & launch
  - mkdir -p /opt/postgres/data
  - docker compose -f /opt/postgres/docker-compose.yml up -d
